# Generated by Django 4.2.3 on 2023-07-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_post_postcategory_post_category_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загрузить картинку для новости'),
        ),
    ]
