# Generated by Django 4.2.3 on 2023-07-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscriber_c',
        ),
    ]
