# Generated by Django 4.2.3 on 2023-07-22 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_category_subscriber_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriber_c',
            field=models.ManyToManyField(blank=True, through='app.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
