# Generated by Django 4.2.3 on 2023-08-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_subscriber_category_alter_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.post'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_category', to='app.category'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
